command = "bundle exec rspec"
arguments = "--format progress --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --force-color"
rerun_arguments = "--format documentation --force-color"
persistence_file = "spec/examples.txt"

 [github]
 owner = "rwojsznis"
 repo = "rspec-sanity-example"
 labels = ['flaky-spec 💩', 'automation']
 reopen = true
 template = '''
 [Failed build]({{ .Env.CIRCLE_BUILD_URL }})

 Node: `{{ .Env.CIRCLE_NODE_INDEX }}`
 Branch: `{{ .Env.CIRCLE_BRANCH }}`

 | Example |
 | --- |
 {{- range .Examples}}
 | {{ .Id }} |
 {{- end}}
 '''
